### PR TITLE
Social media website - Milestone: friendships v1

### PR DESCRIPTION
**Pull request by vicmaburrito**
Implement friendships with 2 rows for mutual friendship.

### CODE REVIEW

**Review by elisha2kyakpo1 — CHANGES_REQUESTED** [review]
# Status: Changes required 👈
Hey, @vicmaburrito this project is almost complete, I was happy to see a lot of features being implemented.

**To highlight:**

- A user can send a friendship request
- A user can accept a friendship request.
- A user can only see posts done by the same user(logged in) and of their friends.
- There is a button to invite user to friendship on users list page and on single user page.

### Changes to make

- [x] User can reject a friendship request, currently, when I try to click on reject friendship request, I get the error in the image below.
friendDecline

- [x] add Unit and Integration tests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

**When you are done making changes, submit another review request**

<hr>
**Reach out to me by commenting under this PR, if you have any questions regarding the review**

# Cheers and happy coding🎉🎉
Elisha

**Comment by vicmaburrito** [comment]
Feedback on the RSpec test would be helpful to fix the tests

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :red_circle: :stop_sign: 
--------------
Hello @vicmaburrito, Great job working on the required changes :+1: :muscle: 
However, you need to work on some minor changes :hammer_and_wrench: see them below :eyes: :point_down: 
---------------

- [x] Fix the failures in the rspec. 

For the problem, you got on the rspec. Instead of run `rspec` run `bundle exec rspec` with this, the test will run. 

--------------
Make these required changes and send it again for another review :muscle: :+1: 
HAPPY CODING!!

**Review by mke2111 — APPROVED** [review]
# 😄 🥇  STATUS: APPROVED  🥇 👏🏽 

## Hey Happy Coder, 👋🏽 
Congratulations, 🥂 . You got minimum requirements for approval. 👍🏽 

### **_Well Done_** 💯 

    1. The tests run just fine. 👍🏽 

### You may now merge to the develop branch and remember to submit a project completion form.
### I wish you the very best in your upcoming projects.

**Cheers 🍹 and Happy coding 💻** 

<hr>

### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

**Pull request merged**
