### PR TITLE
Add ERD for stay in touch project

### PR DESCRIPTION
**Pull request by vicmaburrito**
### First milestone.
Project completed with [Lucidchart](https://lucid.app/).

Includes:

Private and Foreign keys
Use of requester and requestee for friendship model
Reaction to group both likes and dislikes

### CODE REVIEW

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Invalid 🔴 
Please make sure that github action is running.
Ask for new CR when it is ready 😄

**Comment by vicmaburrito** [comment]
Hello, I have an issue that I have not been able to solve about the linter, on my local computer rubocop and stylelint work correctly, but when I push I don't know the reason why they do not appear in the pull request, it could be of great help that  you could give me some advice to solve this problem

**Review by bini-i — CHANGES_REQUESTED** [review]
# Status: Invalid :red_circle:           
### Hello @vicmaburrito  :wave: 

You should make sure that your repo looks professional before review. Currently, Github actions are not running, please make sure they are running before submitting a review. This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

> hint: First, make sure workflows are allowed to run by enabling them under `Actions` tab in your repo. as shown below. 
image
Second, make sure your linter.yml file matches [this](https://github.com/microverseinc/linters-config/blob/master/ror/.github/workflows/linters.yml).
Hope it helps!

#### If you have any question feel free to ask within the PR and ping me on slack @Binyam Hailemeskel

### HAPPY CODING :computer: :blush: 

> #### Reviewed by Binyam Hailemeskel (Code Reviewer)
> GitHub: [@bini-i](https://github.com/bini-i) 
> Twitter: [@binyamshewa](https://twitter.com/binyamshewa)
> LinkedIn: [LinkedIn](https://www.linkedin.com/in/binyam-hailemeskel-728048151/)

**Review by eliasecasta — APPROVED** [review]
## Status: Approved 🟢

Hello @vicmaburrito, 

Well done with the ERD diagram, I will leave you some extra feedback that you don't need to do but I would advice doing so:

[OPTIONAL]:

- [ ] Your reactions table should be okay without the like and dislike booleans, unless you have something else planned I would recommend you to remove them.
- [ ] I would also recommend you/request you to change your pdf file format to an image like jpg or take a screenshot to it and append it additionally to the docs folder because the pdf needs to be downloaded in order to be opened, contrary to an image which can be seen without an issue directly from the browser.

Good luck with your next milestones!

**Pull request merged**
